### ISSUE TITLE
bug: locks version when installing without version

### ISSUE THREAD

**Issue by kenjis** [CodeIgniter/phpstan-codeigniter#10]
### PHP Version

8.1

### PHPStan CodeIgniter Version

v1.4.2.70400

### PHPStan Version

1.10.39

### What happened?

```console
$ composer require --dev codeigniter/phpstan-codeigniter
```

```diff
--- a/composer.json
+++ b/composer.json
@@ -19,6 +19,7 @@
     "s9e/text-formatter": "^2.13"
   },
   "require-dev": {
+    "codeigniter/phpstan-codeigniter": "v1.4.2.70400",
     "codeigniter4/devkit": "^1.1",
     "mockery/mockery": "^1.6",
     "phpstan/phpstan-mockery": "^1.1",
```

### Minimum Reproduction Script

```console
$ composer require --dev codeigniter/phpstan-codeigniter
```

### Expected Output

`"codeigniter/phpstan-codeigniter": "^1.4",`

**Comment by paulbalandan** [comment]
I sent a bug report to composer: https://github.com/composer/composer/issues/11716

**Comment by MGatner** [comment]
Wow, a Composer bug in the wild! Kinda cool.

**Comment by kenjis** [comment]
`1.4.2.70400` does not follow Semantic Versioning.
https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions
So not a bug?

**Comment by paulbalandan** [comment]
Composer accepts 4 parts in tags. Semver does not accept 4 parts.

**Comment by paulbalandan** [comment]
> I sent a bug report to composer: [composer/composer#11716](https://github.com/composer/composer/issues/11716)

Fix was made 15 minutes ago and will be part of composer v2.6
